export type FleetEquipmentCatalogItem = {
  id: string;
  model: string;
};

/**
 * Frota operacional importada da relacao fornecida pela TransJap.
 * A identificacao (placa/serie) nao e exibida nos cards atuais e, portanto,
 * nao integra este cadastro resumido de frota e maquina.
 */
export const FLEET_EQUIPMENT_CATALOG: readonly FleetEquipmentCatalogItem[] = [
  { id: "FR-016", model: "Carreta Prancha - Carrega Tudo 2 eixos" },
  { id: "FR-018", model: "Caminhão Truk - Mercedes Bens L 1621" },
  { id: "FR-020", model: "Caminhão Truk - Mercedes Benz L 1618" },
  { id: "FR-022", model: "Caminhão Truk - Mercedes Benz L 1620" },
  { id: "FR-024", model: "Caminhão Truk - Mercedes Benz L 1620" },
  { id: "FR-026", model: "Caminhão Truk - Mercedes Benz L 1517" },
  { id: "FR-028", model: "Caminhão Truk - Mercedes Bens L 1518" },
  { id: "FR-030", model: "Caminhão Prancha - Mercedes Benz L 1317" },
  { id: "FR-032", model: "Trator de Pneus" },
  { id: "FR-034", model: "Trator de esteiras - D30E" },
  { id: "FR-036", model: "Carregadeira de rodas - 924-F" },
  { id: "FR-040", model: "Retro-Escavadeira - 416-D 4x4" },
  { id: "FR-042", model: "Carregadeira de rodas - 924-G" },
  { id: "FR-044", model: "Retro-Escavadeira - 416-D 4x4" },
  { id: "FR-050", model: "Retro-Escavadeira - 416-D 4x4" },
  { id: "FR-052", model: "Retro-Escavadeira - 416-D 4x4" },
  { id: "FR-056", model: "Escavadeira Hidráulica - 312 CL" },
  { id: "FR-058", model: "Escavadeira Hidráulica - 312 CL" },
  { id: "FR-060", model: "Escavadeira Hidráulica - 312 DL" },
  { id: "FR-062", model: "Escavadeira Hidráulica - 312 DL" },
  { id: "FR-068", model: "Caminhão Pipa - Ford F12000" },
  { id: "FR-070", model: "Moto Niveladora - 120H" },
  { id: "FR-074", model: "Escavadeira Hidráulica - 312 DL" },
  { id: "FR-076", model: "Escavadeira Hidráulica - 320 CL" },
  { id: "FR-078", model: "Caminhão Pipa - Mercedes Benz L 1218 R" },
  { id: "FR-080", model: "Escavadeira Hidráulica - 320 DL" },
  { id: "FR-084", model: "Retro-Escavadeira - 416-E 4x4" },
  { id: "FR-086", model: "Moto Niveladora - 120K" },
  { id: "FR-088", model: "Moto Niveladora - 120K" },
  { id: "FR-090", model: "Rolo Compactador - CP533E" },
  { id: "FR-092", model: "Mini-carregadeira - 226B2" },
  { id: "FR-094", model: "Escavadeira Hidráulica - 320 DL" },
  { id: "FR-108", model: "Mini-escavadeira - 302.5" },
  { id: "FR-118", model: "Mini-escavadeira - 302.5" },
  { id: "FR-120", model: "Escavadeira Hidráulica - 336 DL" },
  { id: "FR-124", model: "Trator de Pneus - A950 4x4" },
  { id: "FR-128", model: "Trator de esteiras - D6N" },
  { id: "FR-130", model: "Trator de esteiras - D5E" },
  { id: "FR-136", model: "Compressor de Ar" },
  { id: "FR-142", model: "Caminhão Pipa - Volvo VM 330" },
  { id: "FR-160", model: "Escavadeira Hidráulica - 336 DL" },
  { id: "FR-168", model: "Gerador Stemac" },
  { id: "FR-192", model: "Comboio - Mercedes Benz Accelo 1016" },
  { id: "FR-194", model: "Escavadeira Hidráulica - 336 DL" },
  { id: "FR-196", model: "Escavadeira Hidráulica - 336 DL" },
  { id: "FR-198", model: "Escavadeira Hidráulica - 336 DL" },
  { id: "FR-206", model: "Trator de Esteiras - D6T" },
  { id: "FR-214", model: "Caminhão Pipa - Volvo VM 330" },
  { id: "FR-220", model: "Gerador Caterpillar GEP 50-7" },
  { id: "FR-222", model: "Carreta Prancha - Carrega Tudo 3 eixos" },
  { id: "FR-224", model: "Acabadora EAR-800" },
  { id: "FR-226", model: "Caminhão Pipa - Volkswagen 31259" },
  { id: "FR-228", model: "Escavadeira Hidráulica - 320" },
  { id: "FR-230", model: "Escavadeira Hidráulica - 320" },
  { id: "FR-232", model: "Escavadeira Hidráulica - 336" },
  { id: "FR-234", model: "Rompedor Hidraulico" },
  { id: "FR-236", model: "Escavadeira Hidráulica - 130G" },
  { id: "FR-238", model: "Escavadeira Hidráulica - 130G" },
  { id: "FR-240", model: "Motoniveladora 140GC" },
  { id: "FR-242", model: "Motoniveladora 140GC" },
  { id: "FR-244", model: "Escavadeira Hidráulica - 345 GC" },
  { id: "FR-246", model: "Rolo Compactador Müller - TI 18" },
  { id: "FR-250", model: "Rolo Compactador Hamm" },
  { id: "FR-252", model: "Grade Aradora - 16 discos" },
  { id: "FR-254", model: "Rolo Dynapac DYN 7433 CA 25 D" },
  { id: "FR-256", model: "Rolo Dynapac DYN 7201 CA 30" },
  { id: "FR-258", model: "Trator John Deere" },
  { id: "FR-262", model: "Caminhão Comboio - Mercedes Benz Atego 1418" },
  { id: "FR-264", model: "Motoniveladora New Holland" },
  { id: "FR-266", model: "Caminhão Pipa - Mercedes Benz Actros 4844 2011" },
  { id: "FR-268", model: "Escavadeira Hidráulica - Volvo" },
  { id: "FR-270", model: "Moto Bomba" },
  { id: "FR-274", model: "Rolo Compactador Hamm" },
  { id: "FR-278", model: "Moto Bomba" },
  { id: "FR-282", model: "Trator Valtra BM135 4x4 Cabinado" },
  { id: "FR-284", model: "Trator Valtra BM135 4x4" },
  { id: "FR-286", model: "Grade do girico 16 discos" },
  { id: "FR-288", model: "Grade" },
  { id: "FR-290", model: "Moto Niveladora 140" },
  { id: "FR-292", model: "Automóvel - Fiat Fiorino Endurance" },
  { id: "FR-294", model: "Automóvel - CHEV ONIX 10TAT HB" },
];
