WITH fleet_location (id, model, location) AS (
  VALUES
    ('FR-070', 'Moto Niveladora - 120H', 'CAMPO LOG 5'),
    ('FR-074', 'Escavadeira Hidraulica - 312 DL', 'CAMPO LOG 5'),
    ('FR-084', 'Retro-Escavadeira - 416-E 4x4', 'CAMPO LOG 5'),
    ('FR-088', 'Moto Niveladora - 120K', 'CAMPO LOG 5'),
    ('FR-124', 'Trator Pneus - A950 4x4', 'CAMPO LOG 5'),
    ('FR-128', 'Trator de esteiras - D6N', 'CAMPO LOG 5'),
    ('FR-142', 'Volvo VM 330', 'CAMPO LOG 5'),
    ('FR-156', 'Mercedes Benz AXOR', 'CAMPO LOG 5'),
    ('FR-164', 'Hillux CD 4X4 STD', 'CAMPO LOG 5'),
    ('FR-168', 'Gerador', 'CAMPO LOG 5'),
    ('FR-192', 'Caminhao Comboio', 'CAMPO LOG 5'),
    ('FR-194', 'Escavadeira Hidraulica - 336 DL', 'CAMPO LOG 5'),
    ('FR-200', 'Mercedes Benz AXOR 2644', 'CAMPO LOG 5'),
    ('FR-204', 'Micro Onibus', 'CAMPO LOG 5'),
    ('FR-212', 'Saveiro', 'CAMPO LOG 5'),
    ('FR-218', 'Prisma', 'CAMPO LOG 5'),
    ('FR-232', 'Escavadeira Hidraulica - 336', 'CAMPO LOG 5'),
    ('FR-244', 'Escavadeira Hidraulica - 345 GC', 'CAMPO LOG 5'),
    ('FR-246', 'Rolo Compactador Muller - TI 18', 'CAMPO LOG 5'),
    ('FR-248', 'Saveiro 1.6', 'CAMPO LOG 5'),
    ('FR-250', 'Rolo Compactador Hamm', 'CAMPO LOG 5'),
    ('FR-262', 'Caminhao Comboio', 'CAMPO LOG 5'),
    ('FR-264', 'Motoniveladora New Holland', 'CAMPO LOG 5'),
    ('FR-266', 'Caminhao pipa', 'CAMPO LOG 5'),
    ('FR-274', 'Rolo Compactador Hamm', 'CAMPO LOG 5'),
    ('FR-278', 'Moto Bomba', 'CAMPO LOG 5'),
    ('FR-280', 'Kia Bongo', 'CAMPO LOG 5'),
    ('FR-282', 'Trator Valtra BM135', 'CAMPO LOG 5'),
    ('FR-292', 'Fiat Fiorino Endurance', 'CAMPO LOG 5'),
    ('FR-294', 'CHEV ONIX', 'CAMPO LOG 5'),
    ('FR-296', 'Moto Bomba', 'CAMPO LOG 5'),
    ('FR-118', 'Mini-escavadeira - 302.5', 'RDG - Contorno'),
    ('FR-214', 'Volvo VM 330', 'ULIHORT'),
    ('FR-230', 'Escavadeira Hidraulica - 320', 'ULIHORT'),
    ('FR-236', 'Escavadeira Hidraulica - 130G', 'ULIHORT'),
    ('FR-240', 'Motoniveladora 140GC', 'ULIHORT'),
    ('FR-242', 'Motoniveladora 140GC', 'ULIHORT'),
    ('FR-256', 'Rolo Dynapac', 'ULIHORT'),
    ('FR-284', 'Trator Valtra BM135', 'ULIHORT'),
    ('FR-068', 'Pipa ford', 'RDG - Viana'),
    ('FR-090', 'Rolo Compactador', 'RDG - Viana'),
    ('FR-182', 'Volvo VM 330', 'RDG - Viana'),
    ('FR-228', 'Escavadeira Hidraulica - 320', 'RDG - Viana'),
    ('FR-238', 'Escavadeira Hidraulica - 130G', 'RDG - Viana'),
    ('FR-254', 'Rolo Dynapac', 'RDG - Viana'),
    ('FR-258', 'Trator John Deere', 'RDG - Viana'),
    ('FR-260', 'Gol branco', 'RDG - Viana'),
    ('FR-268', 'Escavadeira volvo', 'RDG - Viana'),
    ('FR-270', 'Moto Bomba', 'RDG - Viana'),
    ('FR-290', 'Moto Niveladora 140', 'RDG - Viana')
)
INSERT OR IGNORE INTO equipment (
  id,
  model,
  icon,
  hours,
  status,
  tone,
  location,
  last_maintenance,
  series_number,
  acquisition_date,
  manufacturer,
  created_at,
  updated_at
)
SELECT
  id,
  model,
  'construction',
  0,
  'Operação',
  'success',
  location,
  '',
  '',
  '',
  '',
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
  strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
FROM fleet_location;
--> statement-breakpoint
WITH fleet_location (id, model, location) AS (
  VALUES
    ('FR-070', 'Moto Niveladora - 120H', 'CAMPO LOG 5'),
    ('FR-074', 'Escavadeira Hidraulica - 312 DL', 'CAMPO LOG 5'),
    ('FR-084', 'Retro-Escavadeira - 416-E 4x4', 'CAMPO LOG 5'),
    ('FR-088', 'Moto Niveladora - 120K', 'CAMPO LOG 5'),
    ('FR-124', 'Trator Pneus - A950 4x4', 'CAMPO LOG 5'),
    ('FR-128', 'Trator de esteiras - D6N', 'CAMPO LOG 5'),
    ('FR-142', 'Volvo VM 330', 'CAMPO LOG 5'),
    ('FR-156', 'Mercedes Benz AXOR', 'CAMPO LOG 5'),
    ('FR-164', 'Hillux CD 4X4 STD', 'CAMPO LOG 5'),
    ('FR-168', 'Gerador', 'CAMPO LOG 5'),
    ('FR-192', 'Caminhao Comboio', 'CAMPO LOG 5'),
    ('FR-194', 'Escavadeira Hidraulica - 336 DL', 'CAMPO LOG 5'),
    ('FR-200', 'Mercedes Benz AXOR 2644', 'CAMPO LOG 5'),
    ('FR-204', 'Micro Onibus', 'CAMPO LOG 5'),
    ('FR-212', 'Saveiro', 'CAMPO LOG 5'),
    ('FR-218', 'Prisma', 'CAMPO LOG 5'),
    ('FR-232', 'Escavadeira Hidraulica - 336', 'CAMPO LOG 5'),
    ('FR-244', 'Escavadeira Hidraulica - 345 GC', 'CAMPO LOG 5'),
    ('FR-246', 'Rolo Compactador Muller - TI 18', 'CAMPO LOG 5'),
    ('FR-248', 'Saveiro 1.6', 'CAMPO LOG 5'),
    ('FR-250', 'Rolo Compactador Hamm', 'CAMPO LOG 5'),
    ('FR-262', 'Caminhao Comboio', 'CAMPO LOG 5'),
    ('FR-264', 'Motoniveladora New Holland', 'CAMPO LOG 5'),
    ('FR-266', 'Caminhao pipa', 'CAMPO LOG 5'),
    ('FR-274', 'Rolo Compactador Hamm', 'CAMPO LOG 5'),
    ('FR-278', 'Moto Bomba', 'CAMPO LOG 5'),
    ('FR-280', 'Kia Bongo', 'CAMPO LOG 5'),
    ('FR-282', 'Trator Valtra BM135', 'CAMPO LOG 5'),
    ('FR-292', 'Fiat Fiorino Endurance', 'CAMPO LOG 5'),
    ('FR-294', 'CHEV ONIX', 'CAMPO LOG 5'),
    ('FR-296', 'Moto Bomba', 'CAMPO LOG 5'),
    ('FR-118', 'Mini-escavadeira - 302.5', 'RDG - Contorno'),
    ('FR-214', 'Volvo VM 330', 'ULIHORT'),
    ('FR-230', 'Escavadeira Hidraulica - 320', 'ULIHORT'),
    ('FR-236', 'Escavadeira Hidraulica - 130G', 'ULIHORT'),
    ('FR-240', 'Motoniveladora 140GC', 'ULIHORT'),
    ('FR-242', 'Motoniveladora 140GC', 'ULIHORT'),
    ('FR-256', 'Rolo Dynapac', 'ULIHORT'),
    ('FR-284', 'Trator Valtra BM135', 'ULIHORT'),
    ('FR-068', 'Pipa ford', 'RDG - Viana'),
    ('FR-090', 'Rolo Compactador', 'RDG - Viana'),
    ('FR-182', 'Volvo VM 330', 'RDG - Viana'),
    ('FR-228', 'Escavadeira Hidraulica - 320', 'RDG - Viana'),
    ('FR-238', 'Escavadeira Hidraulica - 130G', 'RDG - Viana'),
    ('FR-254', 'Rolo Dynapac', 'RDG - Viana'),
    ('FR-258', 'Trator John Deere', 'RDG - Viana'),
    ('FR-260', 'Gol branco', 'RDG - Viana'),
    ('FR-268', 'Escavadeira volvo', 'RDG - Viana'),
    ('FR-270', 'Moto Bomba', 'RDG - Viana'),
    ('FR-290', 'Moto Niveladora 140', 'RDG - Viana')
)
UPDATE equipment
SET
  model = (
    SELECT fleet_location.model
    FROM fleet_location
    WHERE fleet_location.id = equipment.id
  ),
  location = (
    SELECT fleet_location.location
    FROM fleet_location
    WHERE fleet_location.id = equipment.id
  ),
  status = 'Operação',
  tone = 'success',
  updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id IN (SELECT id FROM fleet_location);
