/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrocaFiltrosDieselRouteImport } from './routes/troca-filtros-diesel'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProducaoConsumoRouteImport } from './routes/producao-consumo'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ManutencaoRouteImport } from './routes/manutencao'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EquipamentosRouteImport } from './routes/equipamentos'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const TrocaFiltrosDieselRoute = TrocaFiltrosDieselRouteImport.update({
  id: '/troca-filtros-diesel',
  path: '/troca-filtros-diesel',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProducaoConsumoRoute = ProducaoConsumoRouteImport.update({
  id: '/producao-consumo',
  path: '/producao-consumo',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ManutencaoRoute = ManutencaoRouteImport.update({
  id: '/manutencao',
  path: '/manutencao',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipamentosRoute = EquipamentosRouteImport.update({
  id: '/equipamentos',
  path: '/equipamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/equipamentos': typeof EquipamentosRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/producao-consumo': typeof ProducaoConsumoRoute
  '/relatorios': typeof RelatoriosRoute
  '/troca-filtros-diesel': typeof TrocaFiltrosDieselRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/equipamentos': typeof EquipamentosRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/producao-consumo': typeof ProducaoConsumoRoute
  '/relatorios': typeof RelatoriosRoute
  '/troca-filtros-diesel': typeof TrocaFiltrosDieselRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/calendario': typeof CalendarioRoute
  '/equipamentos': typeof EquipamentosRoute
  '/estoque': typeof EstoqueRoute
  '/login': typeof LoginRoute
  '/manutencao': typeof ManutencaoRoute
  '/perfil': typeof PerfilRoute
  '/producao-consumo': typeof ProducaoConsumoRoute
  '/relatorios': typeof RelatoriosRoute
  '/troca-filtros-diesel': typeof TrocaFiltrosDieselRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/calendario'
    | '/equipamentos'
    | '/estoque'
    | '/login'
    | '/manutencao'
    | '/perfil'
    | '/producao-consumo'
    | '/relatorios'
    | '/troca-filtros-diesel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/calendario'
    | '/equipamentos'
    | '/estoque'
    | '/login'
    | '/manutencao'
    | '/perfil'
    | '/producao-consumo'
    | '/relatorios'
    | '/troca-filtros-diesel'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/calendario'
    | '/equipamentos'
    | '/estoque'
    | '/login'
    | '/manutencao'
    | '/perfil'
    | '/producao-consumo'
    | '/relatorios'
    | '/troca-filtros-diesel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CalendarioRoute: typeof CalendarioRoute
  EquipamentosRoute: typeof EquipamentosRoute
  EstoqueRoute: typeof EstoqueRoute
  LoginRoute: typeof LoginRoute
  ManutencaoRoute: typeof ManutencaoRoute
  PerfilRoute: typeof PerfilRoute
  ProducaoConsumoRoute: typeof ProducaoConsumoRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TrocaFiltrosDieselRoute: typeof TrocaFiltrosDieselRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/troca-filtros-diesel': {
      id: '/troca-filtros-diesel'
      path: '/troca-filtros-diesel'
      fullPath: '/troca-filtros-diesel'
      preLoaderRoute: typeof TrocaFiltrosDieselRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producao-consumo': {
      id: '/producao-consumo'
      path: '/producao-consumo'
      fullPath: '/producao-consumo'
      preLoaderRoute: typeof ProducaoConsumoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manutencao': {
      id: '/manutencao'
      path: '/manutencao'
      fullPath: '/manutencao'
      preLoaderRoute: typeof ManutencaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipamentos': {
      id: '/equipamentos'
      path: '/equipamentos'
      fullPath: '/equipamentos'
      preLoaderRoute: typeof EquipamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CalendarioRoute: CalendarioRoute,
  EquipamentosRoute: EquipamentosRoute,
  EstoqueRoute: EstoqueRoute,
  LoginRoute: LoginRoute,
  ManutencaoRoute: ManutencaoRoute,
  PerfilRoute: PerfilRoute,
  ProducaoConsumoRoute: ProducaoConsumoRoute,
  RelatoriosRoute: RelatoriosRoute,
  TrocaFiltrosDieselRoute: TrocaFiltrosDieselRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
